spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver  # Ensure this driver class name is correct
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true # I added this most recently
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.earl.payment.notification.PaymentNotificationRequest
server:
  port: 8060