#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/product
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#server:
#  port: 8050