#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/product
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#server:
#  port: 8050
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver  # Ensure this driver class name is correct
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true # I added this most recently
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  cloud:
#    config:
#      enabled: false
server:
  port: 8050