ALTER TABLE ecommerce.category ADD UNIQUE (name);
ALTER TABLE ecommerce.product ADD COLUMN category_name VARCHAR(255) NOT NULL;
ALTER TABLE ecommerce.product ADD CONSTRAINT fk_category_name FOREIGN KEY (category_name) REFERENCES category(name);

INSERT INTO ecommerce.product (id, description, name, available_quantity, price, category_id, category_name) VALUES
(1, 'The latest iPhone with advanced camera system and A15 Bionic chip', 'iPhone 13', 100, 799.99, 1, 'Electronics'),
(2, 'High-performance smartphone with dynamic AMOLED display', 'Samsung Galaxy S21', 150, 699.99, 1, 'Electronics'),
(3, 'Powerful laptop with M1 chip and Retina display', 'MacBook Pro', 50, 1299.99, 1, 'Electronics'),
(4, 'Noise-canceling over-ear headphones with superior sound quality', 'Sony WH-1000XM4 Headphones', 200, 349.99, 1, 'Electronics'),
(5, 'Comfortable and durable running shoes for all terrains', 'Adidas Running Shoes', 300, 89.99, 2, 'Apparel'),
(6, 'Stylish and comfortable sportswear for active lifestyle', 'Nike Sportswear', 250, 59.99, 2, 'Apparel'),
(7, 'Classic and durable denim jeans', 'Levi’s Jeans', 400, 49.99, 2, 'Apparel'),
(8, 'Complete book series of the famous wizard, Harry Potter', 'Harry Potter Book Series', 500, 59.99, 3, 'Books'),
(9, 'Classic novel by Harper Lee about racial injustice', 'To Kill a Mockingbird', 600, 9.99, 3, 'Books'),
(10, 'Classic novel by F. Scott Fitzgerald set in the Jazz Age', 'The Great Gatsby', 700, 14.99, 3, 'Books'),
(11, 'Elegant and modern dining table set for home', 'Dining Table Set', 100, 299.99, 4, 'Home & Kitchen'),
(12, 'Compact and efficient microwave oven for quick meals', 'Microwave Oven', 150, 99.99, 4, 'Home & Kitchen'),
(13, 'High-power vacuum cleaner for effective cleaning', 'Vacuum Cleaner', 200, 89.99, 4, 'Home & Kitchen'),
(14, 'Durable and non-slip yoga mat for all types of yoga', 'Yoga Mat', 250, 29.99, 5, 'Sports & Outdoors'),
(15, 'Official size and weight basketball for indoor and outdoor play', 'Basketball', 300, 19.99, 5, 'Sports & Outdoors'),
(16, 'Lightweight and durable tennis racket for all levels', 'Tennis Racket', 350, 49.99, 5, 'Sports & Outdoors'),
(17, 'Moisturizing face cream for all skin types', 'Face Moisturizer', 400, 19.99, 6, 'Health & Beauty'),
(18, 'Gentle and nourishing shampoo for daily use', 'Shampoo', 450, 9.99, 6, 'Health & Beauty'),
(19, 'Long-lasting lipstick with vibrant color', 'Lipstick', 500, 14.99, 6, 'Health & Beauty'),
(20, 'Creative and fun building set for kids', 'Lego Building Set', 150, 59.99, 7, 'Toys & Games'),
(21, 'Classic Barbie doll with fashionable outfit', 'Barbie Doll', 200, 24.99, 7, 'Toys & Games'),
(22, 'Challenging and entertaining puzzle game for all ages', 'Puzzle Game', 250, 14.99, 7, 'Toys & Games'),
(23, 'Fresh and organic apples for a healthy snack', 'Organic Apples', 300, 2.99, 8, 'Groceries'),
(24, 'Healthy and dairy-free almond milk', 'Almond Milk', 350, 3.99, 8, 'Groceries'),
(25, 'Nutritious and delicious cereal for breakfast', 'Cereal', 400, 4.99, 8, 'Groceries'),
(26, 'High-quality printer paper for all printing needs', 'Printer Paper', 150, 14.99, 9, 'Office Supplies'),
(27, 'Smooth and reliable ballpoint pens for everyday use', 'Ballpoint Pens', 200, 4.99, 9, 'Office Supplies'),
(28, 'Comfortable and ergonomic desk chair for office', 'Desk Chair', 100, 99.99, 9, 'Office Supplies'),
(29, 'Reliable and long-lasting car battery', 'Car Battery', 50, 79.99, 10, 'Automotive'),
(30, 'Durable and effective windshield wipers', 'Windshield Wipers', 100, 14.99, 10, 'Automotive'),
(31, 'High-performance motor oil for car engines', 'Motor Oil', 200, 29.99, 10, 'Automotive'),
(32, 'Portable and powerful Bluetooth speaker with great sound', 'Bluetooth Speaker', 250, 49.99, 1, 'Electronics'),
(33, 'Accurate and reliable fitness tracker with multiple features', 'Fitness Tracker', 150, 99.99, 1, 'Electronics'),
(34, 'High-performance gaming laptop with powerful graphics', 'Gaming Laptop', 100, 1499.99, 1, 'Electronics'),
(35, 'Warm and stylish winter coat for cold weather', 'Winter Coat', 300, 129.99, 2, 'Apparel'),
(36, 'Light and comfortable summer dress', 'Summer Dress', 200, 39.99, 2, 'Apparel'),
(37, 'Stylish and comfortable sneakers for everyday use', 'Sneakers', 400, 59.99, 2, 'Apparel'),
(38, 'Classic novel by J.D. Salinger about teenage angst', 'The Catcher in the Rye', 500, 7.99, 3, 'Books'),
(39, 'Dystopian novel by George Orwell about a totalitarian regime', '1984 by George Orwell', 600, 9.99, 3, 'Books'),
(40, 'Epic novel by Herman Melville about a whaling voyage', 'Moby Dick', 700, 11.99, 3, 'Books'),
(41, 'Efficient coffee maker for a perfect cup of coffee', 'Coffee Maker', 150, 39.99, 4, 'Home & Kitchen'),
(42, 'Powerful and versatile blender for smoothies and soups', 'Blender', 200, 29.99, 4, 'Home & Kitchen'),
(43, 'High-efficiency air purifier for clean air', 'Air Purifier', 100, 99.99, 4, 'Home & Kitchen'),
(44, 'Durable and high-quality soccer ball for all levels', 'Soccer Ball', 300, 19.99, 5, 'Sports & Outdoors'),
(45, 'Spacious and durable camping tent for outdoor adventures', 'Camping Tent', 150, 149.99, 5, 'Sports & Outdoors'),
(46, 'High-quality fishing rod for all fishing enthusiasts', 'Fishing Rod', 200, 49.99, 5, 'Sports & Outdoors'),
(47, 'Moisturizing hand cream for soft and smooth hands', 'Hand Cream', 400, 8.99, 6, 'Health & Beauty'),
(48, 'Nourishing conditioner for healthy and shiny hair', 'Conditioner', 450, 9.99, 6, 'Health & Beauty'),
(49, 'Versatile eye shadow palette with vibrant colors', 'Eye Shadow Palette', 300, 19.99, 6, 'Health & Beauty'),
(50, 'Comfortable and warm jacket perfect for winter', 'Winter Jacket', 200, 99.99, 2, 'Apparel'),
(51, 'Sleek and lightweight laptop with long battery life', 'Dell XPS 13', 75, 1199.99, 1, 'Electronics'),
(52, 'Versatile tablet with powerful performance', 'iPad Pro', 100, 999.99, 1, 'Electronics'),
(53, 'High-quality wireless earbuds with noise cancellation', 'Bose QuietComfort Earbuds', 150, 279.99, 1, 'Electronics'),
(54, 'Lightweight and breathable running shorts', 'Nike Running Shorts', 300, 29.99, 2, 'Apparel'),
(55, 'Stylish smartwatch with fitness tracking features', 'Apple Watch Series 7', 200, 399.99, 1, 'Electronics'),
(56, 'Advanced DSLR camera with 24.2MP sensor', 'Canon EOS Rebel T7', 50, 499.99, 1, 'Electronics'),
(57, 'Comfortable and supportive everyday sneakers', 'Puma Sneakers', 350, 69.99, 2, 'Apparel'),
(58, 'Versatile and spacious backpack for daily use', 'Herschel Backpack', 250, 49.99, 2, 'Apparel'),
(59, 'High-quality gaming console with immersive graphics', 'PlayStation 5', 75, 499.99, 1, 'Electronics'),
(60, 'Ergonomic office chair with lumbar support', 'Ergonomic Office Chair', 150, 199.99, 9, 'Office Supplies'),
(61, 'Compact and powerful blender for smoothies', 'Nutribullet Blender', 200, 89.99, 4, 'Home & Kitchen'),
(62, 'High-resolution monitor with vivid colors', 'Samsung 4K Monitor', 100, 349.99, 1, 'Electronics'),
(63, 'Durable and reliable hard drive for data storage', 'Seagate 2TB External Hard Drive', 300, 79.99, 1, 'Electronics'),
(64, 'Comfortable and supportive mattress for better sleep', 'Memory Foam Mattress', 100, 399.99, 4, 'Home & Kitchen'),
(65, 'Multi-functional printer with wireless connectivity', 'HP OfficeJet Pro 8025', 200, 169.99, 9, 'Office Supplies'),
(66, 'Compact and portable camping stove', 'Coleman Camping Stove', 150, 59.99, 5, 'Sports & Outdoors'),
(67, 'Set of resistance bands for strength training', 'Resistance Bands Set', 300, 29.99, 5, 'Sports & Outdoors'),
(68, 'High-quality electric toothbrush with multiple modes', 'Philips Sonicare Toothbrush', 250, 89.99, 6, 'Health & Beauty'),
(69, 'Powerful cordless vacuum cleaner', 'Dyson V11 Cordless Vacuum', 100, 599.99, 4, 'Home & Kitchen'),
(70, 'Stainless steel cookware set with non-stick coating', 'T-fal Cookware Set', 150, 99.99, 4, 'Home & Kitchen'),
(71, 'Luxurious and hydrating facial serum', 'Vitamin C Serum', 300, 49.99, 6, 'Health & Beauty'),
(72, 'Versatile and powerful food processor', 'Cuisinart Food Processor', 200, 129.99, 4, 'Home & Kitchen'),
(73, 'Comfortable and stylish men’s dress shoes', 'Clarks Dress Shoes', 250, 89.99, 2, 'Apparel'),
(74, 'Set of colorful and durable children’s books', 'Classic Children’s Book Set', 300, 39.99, 3, 'Books'),
(75, 'Durable and spacious luggage for travel', 'Samsonite Luggage', 150, 199.99, 2, 'Apparel'),
(76, 'High-quality yoga mat with non-slip surface', 'Manduka Yoga Mat', 300, 79.99, 5, 'Sports & Outdoors'),
(77, 'Portable and efficient air conditioner', 'LG Portable Air Conditioner', 100, 299.99, 4, 'Home & Kitchen'),
(78, 'Wireless gaming mouse with high precision', 'Logitech G Pro Wireless Mouse', 250, 129.99, 1, 'Electronics'),
(79, 'Comfortable and stylish bed sheets', 'Egyptian Cotton Bed Sheets', 200, 99.99, 4, 'Home & Kitchen'),
(80, 'Noise-canceling earbuds with superior sound quality', 'Sony WF-1000XM3 Earbuds', 150, 199.99, 1, 'Electronics'),
(81, 'Multi-functional smartwatch with health tracking', 'Fitbit Versa 3', 250, 229.99, 1, 'Electronics'),
(82, 'High-performance desktop computer for gaming', 'Alienware Gaming PC', 50, 1999.99, 1, 'Electronics'),
(83, 'Durable and comfortable hiking boots', 'Columbia Hiking Boots', 300, 129.99, 2, 'Apparel'),
(84, 'Advanced robotic vacuum cleaner', 'iRobot Roomba i7', 100, 699.99, 4, 'Home & Kitchen'),
(85, 'Stylish and functional smart glasses', 'Ray-Ban Stories', 200, 299.99, 1, 'Electronics'),
(86, 'Efficient and quiet dishwasher', 'Bosch 300 Series Dishwasher', 50, 849.99, 4, 'Home & Kitchen'),
(87, 'Powerful and versatile hand blender', 'KitchenAid Hand Blender', 250, 59.99, 4, 'Home & Kitchen'),
(88, 'Comfortable and breathable running shoes', 'New Balance Running Shoes', 300, 109.99, 2, 'Apparel'),
(89, 'High-quality soundbar with deep bass', 'Bose Soundbar 700', 100, 799.99, 1, 'Electronics'),
(90, 'Multi-functional smart display with voice control', 'Amazon Echo Show 10', 200, 249.99, 1, 'Electronics'),
(91, 'Luxurious and aromatic essential oil diffuser', 'VicTsing Essential Oil Diffuser', 300, 29.99, 6, 'Health & Beauty'),
(92, 'Ergonomic and adjustable standing desk', 'VariDesk Pro Plus 36', 150, 395.99, 9, 'Office Supplies'),
(93, 'Comfortable and versatile flip-flops', 'Havaianas Flip Flops', 400, 24.99, 2, 'Apparel'),
(94, 'Compact and powerful power bank', 'Anker PowerCore 10000', 300, 39.99, 1, 'Electronics'),
(95, 'Durable and waterproof action camera', 'GoPro HERO9', 100, 399.99, 1, 'Electronics'),
(96, 'Advanced home security camera system', 'Arlo Pro 4', 200, 499.99, 1, 'Electronics'),
(97, 'Comfortable and stylish outdoor patio set', 'Outdoor Patio Set', 100, 499.99, 4, 'Home & Kitchen'),
(98, 'High-quality and eco-friendly laundry detergent', 'Seventh Generation Laundry Detergent', 250, 12.99, 8, 'Groceries'),
(99, 'Durable and leak-proof water bottle', 'Hydro Flask Water Bottle', 400, 39.99, 5, 'Sports & Outdoors'),
(100, 'Versatile and efficient slow cooker', 'Crock-Pot Slow Cooker', 150, 49.99, 4, 'Home & Kitchen');

